import type { Metadata } from 'next';
import './globals.css';
import { archivo, inter, roboto } from '@/lib/fonts';
import { SanityLive } from '@/sanity/lib/live';

export const metadata: Metadata = {
  title: {
    template: '%s | H',
    default: 'Haru&Co',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} ${archivo.variable} antialiased`}
      >
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
